name: remove 'D-DAY' label on approved PR

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  remove-label:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: remove 'D-DAY' labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            async function removeLabels() {
              const prNumber = context.payload.pull_request.number;
              const { owner, repo } = context.repo;

              const { data: reviews } = await github.rest.pulls.listReviews({
                owner,
                repo,
                pull_number: prNumber
              });

              const reviewerStates = new Map();

              for (const review of reviews) {
                reviewerStates.set(review.user.login, review.state);
              }

              const uniqueApprovers = new Set(
                [...reviewerStates.entries()]
                  .filter(([user, state]) => state === 'APPROVED')
                  .map(([user, state]) => user)
              );

              if (uniqueApprovers.size < 2) {
                console.log('Less than 2 unique approvals, no labels removed.');
                return;
              }

              const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                owner,
                repo,
                issue_number: prNumber
              });

              for (const label of labels) {
                if (label.name.startsWith('D-')) {
                  await github.rest.issues.removeLabel({
                    owner,
                    repo,
                    issue_number: prNumber,
                    name: label.name
                  });
                  console.log(`Label ${label.name} removed.`);
                }
              }
            }

            removeLabels().catch(error => {
              console.error('Error removing labels:', error);
              process.exit(1);
            });