export { default as BreadcrumbHeader } from './BreadcrumbHeader.vue';
export { default as StoreNameBox } from './StoreNameBox.vue';
export { default as Loading } from './Loading.vue';
export { default as ExampleMainCategoryMenu } from './ExampleMainCategoryMenu.vue';
export { default as ExampleSubCategoryMenu } from './ExampleSubCategoryMenu.vue';
export { default as ExampleTableNumber } from './ExampleTableNumber.vue';
export { default as ExampleStaffCallButton } from './ExampleStaffCallButton.vue';
export { default as ExampleButton } from './ExampleButton.vue';
export { default as ExampleBackground } from './ExampleBackground.vue';
