name: Add Label on Pull Request

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @actions/core @actions/github

      - name: Run script to add or update label
        run: node ./.github/workflows/add-label.js
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}