# .github/workflows/other-repo.yml
name: call action_bot.yml

on:
  pull_request:
    types: [opened, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  schedule:
    - cron: '59 22 * * 1-5'  # 매주 월~금요일까지 한국 시간 07:59에 실행
    - cron: '1 15 * * 1-5'   # 매주 월~금요일까지 한국 시간 00:01에 실행
  push:
    tags:
      - 'v*'  # 'v'로 시작하는 태그 푸시에 대해 트리거

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/action_bot.yml
    secrets: inherit