# .github/workflows/other-repo.yml
name: call action_bot.yml

on:
  pull_request:
    types: [opened, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  schedule:
    - cron: '59 22 * * 1-5'  # 매주 월~금요일까지 한국 시간 07:59에 실행
    - cron: '1 15 * * 1-5'   # 매주 월~금요일까지 한국 시간 00:01에 실행
    - cron: '30 0 * * *'
    - cron: '40 0 * * *'
    - cron: '50 0 * * *'
    - cron: '0 1 * * *'
    - cron: '10 1 * * *'
    - cron: '20 1 * * *'
    - cron: '30 1 * * *'
    - cron: '40 1 * * *'
    - cron: '50 1 * * *'
    - cron: '0 2 * * *'
    - cron: '10 2 * * *'
    - cron: '20 2 * * *'
    - cron: '30 2 * * *'
    - cron: '40 2 * * *'
    - cron: '50 2 * * *'
    - cron: '0 3 * * *'
    - cron: '10 3 * * *'
    - cron: '20 3 * * *'
    - cron: '30 3 * * *'
    - cron: '40 3 * * *'
    - cron: '50 3 * * *'
    - cron: '0 4 * * *'
    - cron: '10 4 * * *'
    - cron: '20 4 * * *'
    - cron: '30 4 * * *'
    - cron: '40 4 * * *'
    - cron: '50 4 * * *'
    - cron: '0 5 * * *'
    - cron: '10 5 * * *'
    - cron: '20 5 * * *'
    - cron: '30 5 * * *'
    - cron: '40 5 * * *'
    - cron: '50 5 * * *'
    - cron: '0 6 * * *'
    - cron: '10 6 * * *'
    - cron: '20 6 * * *'
    - cron: '30 6 * * *'
    - cron: '40 6 * * *'
    - cron: '50 6 * * *'
    - cron: '0 7 * * *'
    - cron: '10 7 * * *'
    - cron: '20 7 * * *'
    - cron: '30 7 * * *'
    - cron: '40 7 * * *'
    - cron: '50 7 * * *'
    - cron: '0 8 * * *'
    - cron: '10 8 * * *'
    - cron: '20 8 * * *'
    - cron: '30 8 * * *'
    - cron: '40 8 * * *'
    - cron: '50 8 * * *'
  push:
    tags:
      - 'v*'  # 'v'로 시작하는 태그 푸시에 대해 트리거

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/action_bot.yml
    secrets: inherit