name: check merge condition

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: '0 * * * *' # 매 시간 정각에 실행

jobs:
  check-merge-conditions:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: get pr reviews
        id: get-reviews
        uses: actions/github-script@v7
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            core.setOutput('approvedCount', reviews.filter(review => review.state === 'APPROVED').length);

      - name: Check for required approvals or label
        id: check-conditions
        uses: actions/github-script@v7
        with:
          script: |
            const approvals = parseInt(core.getInput('APPROVED_COUNT'));
            const hasLabel = context.payload.pull_request.labels.map((label) => label.name).includes('D-0');
            
            if (approvals >= 2 || hasLabel) {
              core.setOutput('mergeable', true);
              return;
            }
            
            core.setOutput('mergeable', false);
        env:
          APPROVED_COUNT: ${{ steps.get-reviews.outputs.approvedCount }}

      - name: Update commit status to success
        if: steps.check-conditions.outputs.mergeable == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'success',
              description: 'Ready to merge',
              context: 'merge-check'
            });
            
            console.log('is OK to merge');

      - name: Update commit status to failure
        if: steps.check-conditions.outputs.mergeable == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'failure',
              description: 'Not ready to merge',
              context: 'merge-check'
            });
            
            console.log('is OK to merge');