name: Deploy to Develop

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'develop'
        type: string
      label:
        description: 'Label to deploy'
        required: true
        default: 'origin'
        type: choice
        options:
          - origin
          - global
          - uplus
          - brand1
          - partners

jobs:
  check_branch_exists:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch exists
        id: check_branch
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: branches } = await github.git.listMatchingRefs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/' + github.event.inputs.branch
            });
            const branchExists = branches.length > 0 ? 'true' : 'false';
            console.log(`::set-output name=branch_exists::${branchExists}`);
            if (branches.length > 0) {
              console.log(`::set-output name=branch_name::${github.event.inputs.branch}`);
            }

  deploy_origin:
    runs-on: ubuntu-latest
    if: github.event.inputs.label == 'origin' && steps.check_branch.outputs.branch_exists == 'true'
    needs: check_branch_exists
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.check_branch.outputs.branch_name }}

      - name: Echo Deployment Information
        run: |
          echo "Selected label: ${{ github.event.inputs.label }}"
          echo "Branch to deploy: ${{ github.event.inputs.branch }}"  
          echo "Unique identifier of branch: ${{ github.sha }}"