name: deploy live

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag to deploy'
        required: true
        default: 'v'
        type: string
      label:
        description: 'label to deploy'
        required: true
        default: 'TORDER'
        type: choice
        options:
          - ALL
          - TORDER
          - SAAS
          - GLOBAL
          - UPLUS
          - SINGAPORE
          - US1
          - SYDNEY
          - PARTNERS

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.check_tag.outputs.tag_exists }}
      tag_name: ${{ steps.check_tag.outputs.tag_name }}
    steps:
      - name: Check if tag exists
        id: check_tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tagName = '${{ github.event.inputs.tag }}';
            console.log('tagName',tagName)
            
            const { data: tag } = await github.request('GET /repos/{owner}/{repo}/git/refs/tags/{tag}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tagName
            });

            if (tag) {
              core.setOutput('tag_exists', 'true');
              core.setOutput('tag_name', tagName);
            } else {
              core.setOutput('tag_exists', 'false');
            }

  build:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.tag_exists == 'true' }}
    steps:
      - name: check out branch
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.setup.outputs.tag_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: cache node modules
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-admin-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: install dependencies
        run: yarn

      - name: TORDER
        if: ${{ github.event.inputs.label == 'TORDER' || github.event.inputs.label == 'ALL' }}
        run: |
          echo "building for TORDER"
#          yarn origin:build:live
#
#      - name: UPLUS
#        if: ${{ github.event.inputs.label == 'UPLUS' || github.event.inputs.label == 'ALL' || github.event.inputs.label == 'SAAS' }}
#        run: |
#          echo "building for UPLUS"
#          yarn uplus:build:live
#
#      - name: SINGAPORE
#        if: ${{ github.event.inputs.label == 'SINGAPORE' || github.event.inputs.label == 'ALL' || github.event.inputs.label == 'GLOBAL' }}
#        run: |
#          echo "building for SINGAPORE"
#          yarn sg:build:live
#
#      - name: US1
#        if: ${{ github.event.inputs.label == 'US1' || github.event.inputs.label == 'ALL' || github.event.inputs.label == 'GLOBAL' }}
#        run: |
#          echo "building for US1"
#          yarn us_east:build:live
#
#      - name: SYDNEY
#        if: ${{ github.event.inputs.label == 'SYDNEY' || github.event.inputs.label == 'ALL' || github.event.inputs.label == 'GLOBAL' }}
#        run: |
#          echo "building for SYDNEY"
#          yarn sydney:build:live
#
#      - name: PARTNERS
#        if: ${{ github.event.inputs.label == 'PARTNERS' || github.event.inputs.label == 'ALL' }}
#        run: |
#          echo "building for PARTNERS"
#          yarn partners:build:live
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: TORDER
        if: ${{ github.event.inputs.label == 'TORDER' || github.event.inputs.label == 'ALL' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_LIVE_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_LIVE_DISTRIBUTION_ID }}
        run: |
          echo "deploying to TORDER"
          yarn deploy:action

      - name: UPLUS
        if: ${{ github.event.inputs.label == 'UPLUS' || github.event.inputs.label == 'ALL' || github.event.inputs.label == 'SAAS' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_LIVE_UPLUS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_LIVE_UPLUS_DISTRIBUTION_ID }}
        run: |
          echo "deploying to UPLUS"
          yarn deploy:action

      - name: SINGAPORE
        if: ${{ github.event.inputs.label == 'SINGAPORE' || github.event.inputs.label == 'ALL' || github.event.inputs.label == 'GLOBAL' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_SG_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_SG_REGION }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_SG_DISTRIBUTION_ID }}
        run: |
          echo "deploying to SINGAPORE"
          yarn deploy:action

      - name: US1
        if: ${{ github.event.inputs.label == 'US1' || github.event.inputs.label == 'ALL' || github.event.inputs.label == 'GLOBAL' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_LIVE_US1_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_US_EAST_REGION }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_LIVE_US1_DISTRIBUTION_ID }}
        run: |
          echo "deploying to US1"
          yarn deploy:action

      - name: SYDNEY
        if: ${{ github.event.inputs.label == 'SYDNEY' || github.event.inputs.label == 'ALL' || github.event.inputs.label == 'GLOBAL' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_SYDNEY_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_SYDNEY_REGION }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_SYDNEY_DISTRIBUTION_ID }}
        run: |
          echo "deploying to SYDNEY"
          yarn deploy:action

      - name: PARTNERS
        if: ${{ github.event.inputs.label == 'PARTNERS' || github.event.inputs.label == 'ALL' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_LIVE_US1_PARTNERS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_US_EAST_REGION }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_LIVE_US1_PARTNERS_DISTRIBUTION_ID }}
        run: |
          echo "deploying to PARTNERS"
          yarn deploy:action