name: Deploy to Develop

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'develop'
        type: string
      label:
        description: 'Label to deploy'
        required: true
        default: 'origin'
        type: choice
        options:
          - origin
          - global
          - uplus
          - brand1
          - partners

jobs:
  check_branch_exists:
    runs-on: ubuntu-latest
    outputs:
      branch_exists: ${{ steps.set_branch_exists.outputs.branch_exists }}
      branch_name: ${{ steps.set_branch_exists.outputs.branch_name }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Check if branch exists
        id: check_branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = '${{ github.event.inputs.branch }}';
            const { data: branch } = await github.request('GET /repos/{owner}/{repo}/branches/{branch}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: branchName
            });
            
            if (branch) {
              core.exportVariable('BRANCH_EXISTS', 'true');
              core.exportVariable('BRANCH_NAME', branchName);
            } else {
              core.exportVariable('BRANCH_EXISTS', 'false');
            }

      - name: Set branch exists output
        id: set_branch_exists
        run: |
          echo "branch_exists=${{ env.BRANCH_EXISTS }}" >> $GITHUB_ENV
          echo "branch_name=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV

  deploy_origin:
    runs-on: ubuntu-latest
    needs: check_branch_exists
    steps:
      - name: Check branch_exists
        run: |
          echo ${{needs.check_branch_exists.outputs.branch_exists}}
          echo ${{github.event.inputs.label}}
          if [ "${{ needs.check_branch_exists.outputs.branch_exists }}" == "true" ] && [ "${{ github.event.inputs.label }}" == "origin" ]; then
            echo "Deploying origin"
            exit 0
          else
            echo "Conditions not met for deploying origin"
            exit 1
          fi

      - name: check out repository
        if: always()
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.check_branch_exists.outputs.branch_name }}

      - name: echo
        if: always()
        run: |
          echo "Selected label: ${{ github.event.inputs.label }}"
          echo "Branch to deploy: ${{ github.event.inputs.branch }}"  
          echo "Unique identifier of branch: ${{ github.sha }}"