name: CICD development

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to deploy'
        required: true
        default: 'develop'
        type: string
      label:
        description: 'label to deploy'
        required: true
        default: 'TORDER'
        type: choice
        options:
          - ALL
          - TORDER
          - UPLUS
          - BRAND1

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.check_branch.outputs.branch_name }}
    steps:
      - name: check if branch exists
        id: check_branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const branchName = '${{ github.event.inputs.branch }}';
            console.log('branchName', branchName);
            
            const { data: branch } = await github.request('GET /repos/{owner}/{repo}/branches/{branch}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: branchName
            });
            
            if (branch) {
              core.setOutput('branch_name', branchName);
            }

      - name: check out branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.check_branch.outputs.branch_name }}

      - name: setup node version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

  #----------------------------------------------------------- torder
  build_torder:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ github.event.inputs.label == 'TORDER' || github.event.inputs.label == 'ALL' }}
    steps:
      - name: install dependencies
        run: yarn install

      - name: build TORDER
        run: |
          echo "building for TORDER"
          yarn origin:build:dev

      - name: zip workspace
        run: zip -r workspace.zip .

      - name: upload zipped workspace as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: workspace.zip

  deploy_torder:
    runs-on: ubuntu-latest
    needs: build_torder
    steps:
      - name: download necessary files artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace
          path: ./

      - name: extract workspace
        run: unzip workspace.zip

      - name: deploy TORDER
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_DEV_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "deploying to TORDER"
          yarn deploy:action