name: CICD staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to deploy'
        required: true
        default: 'develop'
        type: string
      label:
        description: 'label to deploy'
        required: true
        default: 'TORDER'
        type: choice
        options:
          - ALL
          - TORDER
          - UPLUS

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch_exists: ${{ steps.check_branch.outputs.branch_exists }}
      branch_name: ${{ steps.check_branch.outputs.branch_name }}
    steps:
      - name: check if branch exists
        id: check_branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = '${{ github.event.inputs.branch }}';
            console.log('branchName',branchName)
            
            const { data: branch } = await github.request('GET /repos/{owner}/{repo}/branches/{branch}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: branchName
            });

            if (branch) {
              core.setOutput('branch_exists', 'true');
              core.setOutput('branch_name', branchName);
            } else {
              core.setOutput('branch_exists', 'false');
            }

      - name: check out branch
        if: ${{ steps.check_branch.outputs.branch_exists == 'true' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.check_branch.outputs.branch_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: cache node modules
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-admin-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: install dependencies
        run: yarn

  build_torder:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.branch_exists == 'true' && (github.event.inputs.label == 'TORDER' || github.event.inputs.label == 'ALL') }}
    steps:
      - name: build TORDER
        run: |
          echo "building for TORDER"
          yarn origin:build:staging

  build_uplus:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.branch_exists == 'true' && (github.event.inputs.label == 'UPLUS' || github.event.inputs.label == 'ALL') }}
    steps:
      - name: build UPLUS
        run: |
          echo "building for UPLUS"
          yarn uplus:build:staging

  deploy_torder:
    runs-on: ubuntu-latest
    needs: build_torder
    if: ${{ github.event.inputs.label == 'TORDER' || github.event.inputs.label == 'ALL' }}
    steps:
      - name: deploy TORDER
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "deploying to TORDER"
          yarn deploy:action

  deploy_uplus:
    runs-on: ubuntu-latest
    needs: build_uplus
    if: ${{ github.event.inputs.label == 'UPLUS' || github.event.inputs.label == 'ALL' }}
    steps:
      - name: deploy UPLUS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_STAGE_UPLUS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_STAGE_UPLUS_DISTRIBUTION_ID }}
        run: |
          echo "deploying to UPLUS"
          yarn deploy:action