name: Main Workflow

on:
  pull_request:
    types: [opened, reopened]

jobs:
  call-workflow:
    uses: torder-lkj/pr-test2/.github/workflows/add_label.yml@main
    with:
      github_token: ${{ github.TOKEN }}
