name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewer
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers', {
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            });
            
            if (response.data.length === 0) {
              await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers', {
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                reviewers: ['leee1846']
              });
            }