name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TEST_TOKEN }}
          script: |
            const { data: collaborators } = await github.repos.listCollaborators({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name
            });

            const pullRequestAuthor = context.payload.pull_request.user.login;

            const reviewers = collaborators
              .filter(collaborator => collaborator.login !== pullRequestAuthor)
              .map(collaborator => collaborator.login);

            if (reviewers.length > 0) {
              await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers', {
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                reviewers: reviewers
              });
            } else {
              console.log('No collaborators found to assign as reviewers.');
            }