name: test1

on:
  pull_request:
    types: [opened]

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: test2
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const { data: collaborators } = await github.repos.listCollaborators({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name
            });

            const reviewers = collaborators.map(collaborator => collaborator.login);

            await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers', {
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers
            });