name: Auto Assign

on:
  pull_request:
    types: [opened]

jobs:
  auto-asign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TEST_TOKEN }}
          script: |
            const { data: collaborators } = await github.repos.listCollaborators({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name
            });
            
            const pullRequestAuthor = context.payload.pull_request.user.login;

            // 요청자를 제외한 리뷰어 목록
            const reviewers = collaborators
              .filter(collaborator => collaborator.login !== pullRequestAuthor)
              .map(collaborator => collaborator.login);
            
            // 리뷰어 자동 설정
            if (reviewers.length > 0) {
              await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers', {
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                reviewers: reviewers
              });
            } else {
              console.log('No collaborators found to assign as reviewers.');
            }
            
            // 요청자 자동 설정
            await github.issues.addAssignees({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              assignees: [pullRequestAuthor]
            });