name: Create Release Notes

on:
  push:
    tags:
      - 'v*'  # 'v'로 시작하는 태그 푸시에 대해 트리거

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the previous tag
        id: get_previous_tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const { data: tags } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });
            
            console.log('모든 태그',tags)
            
            // Get current tag name
            const currentTag = context.ref.replace('refs/tags/', '');
            console.log('현재 태그', currentTag);

            // Find the previous tag
            const currentIndex = tags.findIndex(tag => tag.name === currentTag);
            if (currentIndex === -1 || currentIndex === tags.length - 1) {
              console.log('No previous tag found or current tag is the oldest tag.');
              core.exportVariable('PREVIOUS_TAG_SHA', '');
              return
            }
            
            const previousTag = tags[currentIndex + 1];
            console.log('Previous Tag:', previousTag.name);
            core.exportVariable('PREVIOUS_TAG_SHA', previousTag.commit.sha);

      - name: Get merged pull requests
        id: get_merged_prs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const previousTagSha = process.env.PREVIOUS_TAG_SHA;

            if (!previousTagSha) {
              console.log('No previous tag found.');
              core.exportVariable('MERGED_PR_TITLES', '');
              return;
            }

            // Get commits between previous tag and current tag
            const { data: commits } = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: previousTagSha,
              head: context.sha
            });

            const mergedPRs = [];

            // Find merge commits in the range
            for (const commit of commits.commits) {
              if (commit.commit.message.includes('Merge pull request')) {
                const prNumber = commit.commit.message.match(/#(\d+)/)[1];
                const { data: pr } = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber
                });
                mergedPRs.push(pr);
              }
            }

            if (mergedPRs.length === 0) {
              console.log('No merged pull requests found.');
              core.exportVariable('MERGED_PR_TITLES', '');
            } else {
              const prTitles = mergedPRs.map(pr => `- PR #${pr.number}: ${pr.title} by @${pr.user.login}`).join('\n');
              console.log('Pull 목록:', prTitles);
              core.exportVariable('MERGED_PR_TITLES', prTitles);
            }

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Generate Release Notes
        id: generate_notes
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const prTitles = process.env.MERGED_PR_TITLES;
            console.log('PR Titles:', prTitles);
            if (!prTitles) {
              console.log('No merged pull requests found.');
              return;
            }

            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.ref.replace('refs/tags/', ''),
            });
            console.log('릴리즈:', release);
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              body: `${prTitles}`,
            });

            core.exportVariable('RELEASE_URL', release.html_url);

      - name: Output Release URL
        run: |
          echo "Release URL: $RELEASE_URL"