name: Notify Slack about Pull Requests

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Pull Requests
        id: get-prs
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            let prDetails = pullRequests.map(pr => {
              const dLabel = pr.labels.find(label => label.name.startsWith('D-'));
              if (dLabel) {
                const prLink = `https://github.com/${context.repo.owner}/${context.repo.repo}/pull/${pr.number}`;
                return `<${prLink}|${dLabel.name} - PR #${pr.number}: ${pr.title}>`;
              }
              return null;
            }).filter(prDetail => prDetail !== null).join('\\n');
            
            if (prDetails.length === 0) {
              core.setOutput('hasPrs', 'false');
            } else {
              core.setOutput('hasPrs', 'true');
              core.setOutput('prDetails', prDetails);
            }

      - name: Send to Slack
        if: steps.get-prs.outputs.hasPrs == 'true'
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          mention: "channel"
          custom_payload: |
            {
              "attachments": [
                {
                  "pretext": "Here are the open pull requests:",
                  "title": "${{ github.repository }}",
                  "text": "${{ steps.get-prs.outputs.prDetails }}",
                  "color": "#36a64f"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}