on:
  pull_request:
    types: [opened, reopened]

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Use Add D- Label Action
        uses: torder-lkj/update_d_label@v1.0.1
        with:
          github_token: ${{ secrets.TOKEN }}