name: FRONT 코드리뷰봇

on:
  issue_comment:
    types: [created]

# 작업 그룹화
jobs:
  origin_dev:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: Log event info
        run: echo "This is a pull request comment."