name: Notify Slack on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send notification to Slack
        uses: 8398a7/action-slack@v3
        with:
          payload: |
            {
              "channel": "#your-slack-channel",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "${{ github.event.pull_request.title }}",
                  "title_link": "${{ github.event.pull_request.html_url }}",
                  "text": "Repository: <${{ github.event.repository.html_url }}|${{ github.event.repository.full_name }}>"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}