on:
  pull_request:
    types: [opened, reopened]

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: asdsadsaad
        uses: torder-lkj/notify_slack@v1.0.0
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}