name: test

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  update-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run script to update labels
        uses: actions/github-script@v7
        with:
          script: |
            async function updateLabels() {
              try {
                const { data: prs } = await github.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'open'
                });
                console.log('PRs:', prs);
                for (const pr of prs) {
                  const { data: labels } = await github.issues.listLabelsOnIssue({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number
                  });
                  console.log('Labels:', labels);
                  for (const label of labels) {
                    if (label.name.startsWith('D-')) {
                      console.log('Label starts with "D-"');
                      const currentLabel = parseInt(label.name.slice(2));
                      console.log('Current Label:', currentLabel);
                      if (currentLabel > 0) {
                        const newLabelName = `D-${currentLabel - 1}`;
                        await github.issues.addLabels({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: pr.number,
                          labels: [newLabelName]
                        });
                        await github.issues.removeLabel({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: pr.number,
                          name: label.name
                        });
                      }
                      break;
                    }
                  }
                }
              } catch (error) {
                console.error('Error updating labels:', error);
              }
            }

            updateLabels();
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}