name: Update Label

on:
  pull_request:
    types: [opened, reopened]

jobs:
  update-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get PR Labels
        id: pr-labels
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.request('GET /repos/{owner}/{repo}/issues/{issue_number}/labels', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            const labels = response.data.map(label => label.name);
            console.log('피알의 라벨들', labels);
            core.setOutput('labels', JSON.stringify(labels));

      - name: Update Labels
        uses: actions/github-script@v7
        with:
          script: |
            async function updateLabels() {
              try {
                const prLabels = JSON.parse(process.env.PR_LABELS);
                console.log('PR 라벨들', prLabels);
                for (const label of prLabels) {
                  if (label.startsWith('D-')) {
                    console.log('D-로 시작함');
                    const currentLabel = parseInt(label.slice(2));
                    console.log('Current Label:', currentLabel);
                    if (currentLabel > 0) {
                      const newLabelName = `D-${currentLabel - 1}`;
                      await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        labels: [newLabelName]
                      });
                      await github.rest.issues.removeLabel({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        name: label
                      });
                      console.log(`Label "${label}" updated to "${newLabelName}"`);
                    }
                  }
                }
              } catch (error) {
                console.error('Error updating labels:', error);
              }
            }

            updateLabels();
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_LABELS: ${{ steps.pr-labels.outputs.labels }}