name: FRONT 코드리뷰봇

on:
  pull_request: # PR 생성/재생성시에 D-DAY label 추가
    types: [opened, reopened]

# 작업 그룹화
jobs:
  origin_dev:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: Log event info
        run: echo "This is a pull request comment."