name: Update Label

on:
  pull_request:
    types: [opened, reopened]

jobs:
  update-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update Labels
        uses: actions/github-script@v7
        with:
          script: |
            async function updateLabels() {
              try {
                const { data: labels } = await github.issues.listLabelsForRepo({
                  owner: context.repo.owner,
                  repo: context.repo.repo
                });
                console.log('Labels:', labels);
                for (const label of labels) {
                  if (label.name.startsWith('D-')) {
                    console.log('Label starts with "D-"');
                    const currentLabel = parseInt(label.name.slice(2));
                    console.log('Current Label:', currentLabel);
                    if (currentLabel > 0) {
                      const newLabelName = `D-${currentLabel - 1}`;
                      await github.issues.updateLabel({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        name: label.name,
                        new_name: newLabelName,
                        color: label.color,
                        description: label.description
                      });
                      console.log(`Label "${label.name}" updated to "${newLabelName}"`);
                    }
                  }
                }
              } catch (error) {
                console.error('Error updating labels:', error);
              }
            }

            updateLabels();
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}