#name: test
#
#on:
#  pull_request:
#    types: [opened, edited, reopened]
#
#jobs:
#  add-label:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v3
#
#      - name: Run script to update labels
#        uses: actions/github-script@v7
#        with:
#          script: |
#            const octokit = new Octokit({ auth: ${{ secrets.TOKEN }} });
#
#            const response = await octokit.request('GET /repos/{owner}/{repo}/pulls', {
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              headers: {
#                'X-GitHub-Api-Version': '2022-11-28'
#              }
#            })
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN }}
