name: Update D- Labels

on:
  schedule:
    - cron: '43 6 * * *'  # 매일 한국시간 오후 3시 43분 (UTC 기준 오전 6시 43분)

jobs:
  update-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update D- labels
        uses: actions/github-script@v7
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const github = new Octokit({ auth: process.env.GITHUB_TOKEN });
            const { context } = require("@actions/github");

            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            for (const pr of prs.data) {
              const labels = await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number
              });

              for (const label of labels.data) {
                if (label.name.startsWith('D-')) {
                  const currentLabel = parseInt(label.name.slice(2));
                  if (currentLabel > 0) {
                    const newLabelName = `D-${currentLabel - 1}`;
                    await github.rest.issues.addLabels({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: pr.number,
                      labels: [newLabelName]
                    });
                    await github.rest.issues.removeLabel({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: pr.number,
                      name: label.name
                    });
                  }
                  break;
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}