name: Update Labels

on:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: '38 6 * * *'
    - cron: '41 6 * * *'  # 3분 간격으로 두 번째 실행

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update Labels
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          const { Octokit } = require("@octokit/rest");
          const github = new Octokit({ auth: process.env.GITHUB_TOKEN });
          const { context } = require("@actions/github");

          async function updateLabels() {
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            const { data: labels } = await github.issues.listLabelsOnIssue({
              owner,
              repo,
              issue_number: prNumber,
            });

            for (const label of labels) {
              if (label.name.startsWith('D-')) {
                const currentNumber = parseInt(label.name.split('-')[1]);
                if (currentNumber > 0) {
                  const newLabel = `D-${currentNumber - 1}`;
                  await github.issues.addLabels({
                    owner,
                    repo,
                    issue_number: prNumber,
                    labels: [newLabel],
                  });
                  await github.issues.removeLabel({
                    owner,
                    repo,
                    issue_number: prNumber,
                    name: label.name,
                  });
                }
              }
            }
          }

          updateLabels().catch(error => {
            console.error(`Error updating labels: ${error}`);
            process.exit(1);
          });