name: Update D- Labels

on:
  pull_request:
    types: [opened, edited, reopened]
  schedule:
    - cron: '*/3 * * * *'  # 3분마다 실행됨

jobs:
  update-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update D- Labels
        if: github.event_name == 'pull_request' || github.event_name == 'schedule'
        run: |
          PR_NUMBER=$(jq -r '.pull_request.number' < "${GITHUB_EVENT_PATH}")
          LABELS=$(gh pr view $PR_NUMBER --json labels -q '.labels[].name')
          if echo "$LABELS" | grep -q 'D-'; then
            CURRENT_LABEL=$(echo "$LABELS" | grep -oP '(?<=D-)\d+')
            NEW_LABEL=$((CURRENT_LABEL - 1))
            if [ $NEW_LABEL -ge 0 ]; then
              NEW_LABEL_NAME="D-$NEW_LABEL"
              gh pr edit $PR_NUMBER --add-label "$NEW_LABEL_NAME"
            fi
          fi