name: Update D- Labels Daily

on:
  schedule:
    - cron: '10 8 * * *'  # 매일 오후 5시 10분 (UTC 기준으로)

jobs:
  update-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update D- Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const { data: issues } = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open'
            });

            for (const issue of issues) {
              const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                owner,
                repo,
                issue_number: issue.number
              });

              for (const label of labels) {
                if (label.name.startsWith('D-')) {
                  const number = parseInt(label.name.slice(2), 10);
                  if (number > 0) {
                    const newLabel = `D-${number - 1}`;
                    await github.rest.issues.removeLabel({
                      owner,
                      repo,
                      issue_number: issue.number,
                      name: label.name
                    });
                    await github.rest.issues.addLabels({
                      owner,
                      repo,
                      issue_number: issue.number,
                      labels: [newLabel]
                    });
                    console.log(`Updated label ${label.name} to ${newLabel} for issue ${issue.number}`);
                  }
                }
              }
            }