name: Update D- Labels

on:
  pull_request:
    types: [opened, edited, reopened]
  schedule:
    - cron: '*/2 * * * *'  # 2분마다 실행됨

jobs:
  update-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Update D- Labels
        if: github.event_name == 'pull_request' || github.event_name == 'schedule'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq -r '.pull_request.number' < "${GITHUB_EVENT_PATH}")
          LABELS=$(gh pr view $PR_NUMBER --json labels -q '.labels[].name')
          if echo "$LABELS" | grep -q 'D-'; then
            CURRENT_LABEL=$(echo "$LABELS" | grep -oP '(?<=D-)\d+')
            NEW_LABEL=$((CURRENT_LABEL - 1))
            if [ $NEW_LABEL -ge 0 ]; then
              NEW_LABEL_NAME="D-$NEW_LABEL"
              gh pr edit $PR_NUMBER --add-label "$NEW_LABEL_NAME"
            fi
          fifi