name: Update D- Labels3

on:
  schedule:
    - cron: '*/3 7-23 * * *'  # 매일 한국시간 오후 3시 43분 (UTC 기준 오전 6시 43분)

jobs:
  update-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Node.js 20 버전 사용

      - name: Update D- labels
        uses: actions/github-script@v7
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const githubContext = require("@actions/github").context;

            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            async function updateLabels() {
              const { data: prs } = await octokit.rest.pulls.list({
                owner: githubContext.repo.owner,
                repo: githubContext.repo.repo,
                state: 'open'
              });

              for (const pr of prs) {
                const { data: labels } = await octokit.rest.issues.listLabelsOnIssue({
                  owner: githubContext.repo.owner,
                  repo: githubContext.repo.repo,
                  issue_number: pr.number
                });

                for (const label of labels) {
                  if (label.name.startsWith('D-')) {
                    const currentLabel = parseInt(label.name.slice(2));
                    if (currentLabel > 0) {
                      const newLabelName = `D-${currentLabel - 1}`;
                      await octokit.rest.issues.addLabels({
                        owner: githubContext.repo.owner,
                        repo: githubContext.repo.repo,
                        issue_number: pr.number,
                        labels: [newLabelName]
                      });
                      await octokit.rest.issues.removeLabel({
                        owner: githubContext.repo.owner,
                        repo: githubContext.repo.repo,
                        issue_number: pr.number,
                        name: label.name
                      });
                    }
                    break;
                  }
                }
              }
            }

            updateLabels();
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
