name: Update D- Labels

on:
  pull_request:
    types: [opened, edited, reopened]
  schedule:
    - cron: '*/2 * * * *'  # 매 2분마다 실행

jobs:
  update-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Run JavaScript script to update labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const https = require('https');
          const { readFileSync } = require('fs');
          const { execSync } = require('child_process');

          const GITHUB_EVENT_PATH = process.env.GITHUB_EVENT_PATH;
          const PR_NUMBER = JSON.parse(readFileSync(GITHUB_EVENT_PATH)).pull_request.number;

          const labels = execSync(`gh pr view ${PR_NUMBER} --json labels -q '.labels[].name'`).toString();
          if (labels.includes('D-')) {
            const currentLabel = parseInt(labels.match(/D-(\d+)/)[1]);
            if (currentLabel > 0) {
              const newLabelName = `D-${currentLabel - 1}`;
              execSync(`gh pr edit ${PR_NUMBER} --add-label "${newLabelName}"`);
            }
          }